E-voting System/E-voting System/Models/CirclesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E_voting_System.Models
{
    public class CirclesViewModel
    {
        public int ActiveCircleId { get; set; }
        public List<int> Circles { get; set; }
    }
}

E-voting System/E-voting System/Models/LocalListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E_voting_System.Models
{
    public class LocalListViewModel
    {
        public int? SelectedListId { get; set; }
        public List<int> SelectedCandidateIds { get; set; }
        public List<localList> LocalLists { get; set; }
        public Dictionary<int, List<localCandidate>> CandidatesByList { get; set; }
    }


}

E-voting System/E-voting System/Models/PartyList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PartyList
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "اسم الحزب مطلوب")]

        public string Party_Name { get; set; }
        [Required(ErrorMessage = "اسم القائمة مطلوب")]

        public string List_Name { get; set; }
        [Required(ErrorMessage = "الرقم الوطني للمفوض مطلوب")]
        public int Delegate_ID { get; set; }
        [Required(ErrorMessage = "اسم المفوض مطلوب")]
        public string Delegate_Name { get; set; }
        [Required(ErrorMessage = "رقم الهاتف للمفوض مطلوب")]
        [Phone(ErrorMessage = "رقم الهاتف غير صحيح")]
        public string Delegate_Phone { get; set; }
        [Required(ErrorMessage = "البريد الالكتروني مطلوب")]
        [EmailAddress(ErrorMessage = "البريد الالكتروني غير صالح")]
        public string Delegate_Email { get; set; }
        public int Counter { get; set; }
        public string Status { get; set; }
        public string reason { get; set; }
        public string List_Logo { get; set; }
    }
}

E-voting System/E-voting System/Models/PartyListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace E_voting_System.Models
{
    public class PartyListViewModel
    {
        public int? SelectedPartyId { get; set; }
        public List<PartyList> PartyLists { get; set; }
    }


}

E-voting System/E-voting System/Models/USER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public long National_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Circle_ID { get; set; }
        public string Gender { get; set; }
        public int local_Vote { get; set; }
        public int Party_Vote { get; set; }
        public int White_Local_Vote { get; set; }
        public int White_Party_Vote { get; set; }
    }
}

E-voting System/E-voting System/Models/localList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class localList
    {
        public int ID { get; set; }
        public int Circle_ID { get; set; }
        [Required(ErrorMessage = "اسم القائمة مطلوب")]

        public string list_Name { get; set; }
        //[Required(ErrorMessage = "عدد المرشحين مطلوب")]
        public string list_Candidates { get; set; }
        [Required(ErrorMessage = "الرقم الوطني للمفوض مطلوب")]

        public int Delegate_ID { get; set; }
        [Required(ErrorMessage = "اسم المفوض مطلوب")]
        public string Delegate_Name { get; set; }
        [Required(ErrorMessage = "رقم الهاتف للمفوض مطلوب")]
        [Phone(ErrorMessage = "رقم الهاتف غير صحيح")]
        public string Delegate_Phone { get; set; }
        [Required(ErrorMessage = "البريد الالكتروني مطلوب")]
        [EmailAddress(ErrorMessage = "البريد الالكتروني غير صالح")]
        public string Delegate_Email { get; set; }
        public int Counter { get; set; }
        public string Status { get; set; }
        public string reason { get; set; }
        public string List_Logo { get; set; }
        public Nullable<int> ActualSeats { get; set; }
    }
}

E-voting System/E-voting System/Controllers/userController.cs
using E_voting_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace E_voting_System.Controllers
{
    public class userController : Controller
    {
        private ElectionEntities db = new ElectionEntities();

        // GET: user
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(USER user)
        {
            try
            {
                var userRecord = db.USERS.Find(user.National_ID);

                if (userRecord == null)
                {
                    ModelState.AddModelError("", "User not found.");
                    return View();
                }

                if (userRecord.Password == null)
                {
                    // Generate a random confirmation code
                    Random random = new Random();
                    int randomCode = random.Next(100000, 1000000);
                    Response.Cookies["ConfCode"].Value = randomCode.ToString();
                    Response.Cookies["ConfCode"].Expires = DateTime.Now.AddMinutes(3);

                    // Email settings
                    string fromEmail = "techlearnhub.contact@gmail.com";
                    string toEmail = "qusayomar20@gmail.com"; // Assuming the user record contains the user's email
                    string subjectText = "Your Confirmation Code";
                    string messageText = $"Your confirmation code is {randomCode}";

                    string smtpServer = "smtp.gmail.com";
                    int smtpPort = 587;
                    string smtpUsername = "techlearnhub.contact@gmail.com";
                    string smtpPassword = "lyrlogeztsxclank";

                    // Send the email
                    using (MailMessage mailMessage = new MailMessage())
                    {
                        mailMessage.From = new MailAddress(fromEmail);
                        mailMessage.To.Add(toEmail);
                        mailMessage.Subject = subjectText;
                        mailMessage.Body = messageText;
                        mailMessage.IsBodyHtml = false;

                        using (SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort))
                        {
                            smtpClient.UseDefaultCredentials = false;
                            smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                            smtpClient.EnableSsl = true;

                            smtpClient.Send(mailMessage);
                            Response.Cookies["National_ID"].Value = user.National_ID.ToString();
                             Response.Cookies["National_ID"].Expires = DateTime.Now.AddMinutes(30);

                            ViewBag.Emailsent = "The code has been sent to your Email";
                             

                            return RedirectToAction("EnterCode");
                        }
                    }
                }
                else
                {
                    // User has a password, redirect to prompt for password
                    ViewBag.NationalId = user.National_ID;

                    return RedirectToAction("LoginWithPassword");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while processing your request. Please try again later.");
                Console.WriteLine("Exception message: " + ex.Message);
                Console.WriteLine("Stack trace: " + ex.StackTrace);
                if (ex.InnerException != null)
                {
                    Console.WriteLine("Inner exception message: " + ex.InnerException.Message);
                    Console.WriteLine("Inner exception stack trace: " + ex.InnerException.StackTrace);
                }
            }

            return View();
        }

        public ActionResult EnterCode()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EnterCode(string code)
        {
            var confCodeCookie = Request.Cookies["ConfCode"];

            if (confCodeCookie != null)
            {
                var confCode = confCodeCookie.Value;

                if (code == confCode)
                {
                    return RedirectToAction("ResetPassword");
                }
            }

            ModelState.AddModelError("", "Invalid code.");
            return View();
        }

        public ActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ResetPassword(string NewPassword, string ConfirmPassword)
        {
            // Retrieve National ID from cookies or session
            string National_ID = null;

            if (Request.Cookies["National_ID"] != null)
            {
                National_ID = Request.Cookies["National_ID"].Value;
            }
            else if (Session["National_ID"] != null)
            {
                National_ID = Session["National_ID"].ToString();
            }

            if (National_ID == null)
            {
                ModelState.AddModelError("", "National ID not found.");
                return View();
            }

            if (NewPassword != ConfirmPassword)
            {
                ModelState.AddModelError("", "Passwords do not match.");
                return View();
            }

            var userRecord = db.USERS.Find(int.Parse(National_ID));

            if (userRecord == null)
            {
                ModelState.AddModelError("", "User not found.");
                return View();
            }

            userRecord.Password = NewPassword;
            db.SaveChanges();

            return RedirectToAction("Login");
        }





        public ActionResult LoginWithPassword()
        {
             
            return View();
        }

        [HttpPost]
        public ActionResult LoginWithPassword(string National_ID, string Password)
        {
            var db_record = db.USERS.Find(int.Parse(National_ID));

            if (db_record != null && Password == db_record.Password)
            {
                ViewBag.auth = "";
                Session["National_ID"] = db_record.National_ID; // Ensure this is set as an integer
                return RedirectToAction("TypeOfElection", new { national_id = db_record.National_ID });
            }
            else
            {
                ViewBag.auth = "Password is not correct";
            }

            return View();
        }


        public ActionResult TypeOfElection(int national_id)
        {
            var user_record = db.USERS.Find(national_id);
            var circle_id = user_record.Circle_ID;
            ViewBag.circle = circle_id;

            if (user_record.local_Vote == 0)
            {
                ViewBag.localList_actionName = "LocalList";
            }
            else
            {
                ViewBag.localList_actionName = null;
            }

            if (user_record.Party_Vote == 0)
            {
                ViewBag.PartyList_actionName = "PartyList";
            }
            else
            {
                ViewBag.PartyList_actionName = null;
            }

            return View();
        }

       
        

        public ActionResult PartyList()
        {
            var national_id = Session["National_ID"];
            if (national_id == null)
            {
                return RedirectToAction("Login");
            }

            var partyLists = db.PartyLists.ToList();

            var model = new PartyListViewModel
            {
                PartyLists = partyLists
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult PartyList(PartyListViewModel model)
        {
            if (Session["National_ID"] == null)
            {
                return RedirectToAction("Login");
            }

            int national_id;
            if (!int.TryParse(Session["National_ID"].ToString(), out national_id))
            {
                // Handle the error if the session value cannot be cast to an integer
                ModelState.AddModelError("", "Invalid National ID.");
                return View(model);
            }

            var user = db.USERS.Find(national_id);
            if (user != null)
            {
                if (model.SelectedPartyId.HasValue)
                {
                    var selectedParty = db.PartyLists.Find(model.SelectedPartyId.Value);
                    if (selectedParty != null)
                    {
                        user.Party_Vote = 1; // Update the user's party vote status
                        selectedParty.Counter += 1; // Increment the counter for the selected party
                        db.SaveChanges();
                    }
                }
                else
                {
                    user.Party_Vote = 1; // Update the user's party vote status
                    user.White_Party_Vote = 1; // Update the user's white party vote status
                    db.SaveChanges();
                }
            }

            return RedirectToAction("TypeOfElection", new { national_id = national_id });
        }


        public ActionResult LocalList(int circleId)
        {
            var national_id = Session["National_ID"];
            if (national_id == null)
            {
                return RedirectToAction("Login");
            }

            var user = db.USERS.Find(national_id);
            if (user == null)
            {
                return RedirectToAction("Login");
            }

            // Fetch only the approved local lists for the given circle ID

E-voting System/E-voting System/Views/user/EnterCode.cshtml
@{
    ViewBag.Title = "Enter Code";
}
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap" rel="stylesheet">
<style>
    body {
        font-family: 'Cairo', sans-serif;
    }
</style>
<!-- Enter Code Section ====================== -->
<section class="section-enter-code pt-60 pt-lg-100 pt-xxl-120 pb-40">
    <div class="container">
        <div class="enter-code-form-wrapper bg-custom-light p-4 p-lg-40 shadow-lg rounded card_code" style="box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);">
            <h4 class="mb-30 mb-lg-40 text-lg-center wow fadeInUp">Enter Code</h4>

            @using (Html.BeginForm("EnterCode", "user", FormMethod.Post, new { id = "enterCodeForm", @class = "enter-code-form row g-30 wow slideInUp" }))
            {
                @Html.AntiForgeryToken()

                <div class="col-md-12 mb-3">
                    <label for="Code" class="form-label">Enter the code sent to your email</label>
                    <input type="text" name="code" class="form-control" id="Code" required />
                    @Html.ValidationMessage("code", "", new { @class = "text-danger" })
                </div>

                <div class="col-12 mt-4 card_code_button">
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>
                <div class="response py-1 text-center" style="color: green; font-weight: bold;">@ViewBag.Emailsent</div>
            }
        </div>
        <!-- enter-code-form-wrapper -->
    </div>
    <!-- container -->
</section>
<!-- Enter Code Section ====================== -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#enterCodeForm').on('submit', function (e) {
                e.preventDefault();
                // Add any additional client-side validation or AJAX form submission logic here
                var isValid = true;
                if ($('#Code').val().trim() === '') {
                    $('#Code').addClass('is-invalid');
                    isValid = false;
                } else {
                    $('#Code').removeClass('is-invalid');
                }

                if (isValid) {
                    this.submit();
                }
            });
        });
    </script>
}
<style>
    .card_code_button {
        margin: auto;
        text-align: center;
    }

    .card_code {
        width: 45%;
        margin: auto; /* Ensure the form is centered */
    }

    .shadow-lg {
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2) !important;
    }
</style>

E-voting System/E-voting System/Views/user/LocalList.cshtml
@model E_voting_System.Models.LocalListViewModel

@{
    ViewBag.Title = "القائمة المحلية";
}

<!DOCTYPE html>
<html lang="ar">
<head>
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
        .card {
            cursor: pointer;
            transition: transform 0.3s, box-shadow 0.3s;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

            .card:hover {
                transform: scale(1.05);
                box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);
            }

        .card-body {
            text-align: center;
            padding: 1.5rem;
        }

        .form-check-input {
            margin-top: 0.3em;
        }

        .list-group-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .btn-primary {
            border-radius: 5px;
        }

        h2 {
            font-size: 1.75rem;
            font-weight: 700;
            margin-bottom: 1.5rem;
            color: #333;
            text-align: center;
        }

        .form-group {
            text-align: center;
        }

        .container {
            max-width: 900px;
            margin: 2rem auto; /* Space below navbar */
        }

        body, h1, h2, h3, h4, h5, h6 {
            font-family: 'Cairo', sans-serif;
        }

        .line {
            border-bottom: 3px solid red;
            margin-top: 3px;
            width: 70%;
        }

        .line2 {
            border-bottom: 3px solid darkgreen;
            margin-top: 3px;
            width: 60%;
        }
    </style>
</head>
<body>
    <div class="container">
        <center>
            <h2>التصويت للقوائم المحلية</h2><center><div class="line2"></div><div class="line"></div></center>
        </center><br /><br />
        @using (Html.BeginForm("LocalList", "user", FormMethod.Post, new { id = "localListForm" }))
        {
            @Html.AntiForgeryToken()

            <div class="row">
                @foreach (var list in Model.LocalLists)
                {
                    <div class="col-md-4 mb-4">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">@list.list_Name</h5>
                                @*<img src="@list.List_Logo" alt="شعار @list.list_Name" class="img-fluid my-3" />*@
                                <div class="form-check text-center">
                                    <input class="form-check-input list-radio" type="radio" name="SelectedListId" id="list_@list.ID" value="@list.ID" />
                                    <label class="form-check-label" for="list_@list.ID">
                                        اختر
                                    </label>
                                </div>
                            </div>
                            <div class="card-footer">
                                <h6>المرشحون</h6>
                                <ul class="list-group list-group-flush">
                                    @foreach (var candidate in Model.CandidatesByList[list.ID])
                                    {
                                        <li class="list-group-item">
                                            <div class="form-check">
                                                <input class="form-check-input candidate-checkbox" type="checkbox" name="SelectedCandidateIds" id="candidate_@candidate.CandidateId" value="@candidate.CandidateId" data-list-id="@list.ID" disabled />
                                                <label class="form-check-label" for="candidate_@candidate.CandidateId">
                                                    @candidate.Candidate_Name (@candidate.Type_Of_Chair)
                                                </label>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="form-group mt-4">
                <input type="button" id="submitVote" value="تصويت" style="background-color:#e64141; color: white; padding:15px;" />
            </div>
        }
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var listRadios = document.querySelectorAll('.list-radio');
            var candidateCheckboxes = document.querySelectorAll('.candidate-checkbox');

            listRadios.forEach(function (radio) {
                radio.addEventListener('change', function () {
                    var selectedListId = this.value;

                    candidateCheckboxes.forEach(function (checkbox) {
                        if (checkbox.getAttribute('data-list-id') === selectedListId) {
                            checkbox.disabled = false;
                        } else {
                            checkbox.disabled = true;
                            checkbox.checked = false; // Uncheck the checkbox if it's disabled
                        }
                    });
                });
            });

            document.getElementById('submitVote').addEventListener('click', function () {
                var selectedList = document.querySelector('input[name="SelectedListId"]:checked');
                if (!selectedList) {
                    Swal.fire({
                        title: 'سيُحتسب صوتك كورقة بيضاء',
                        text: "الورقة البيضاء تعني أنك لم تصوّت لأي قائمة, هل تود إكمال عملية التصويت؟",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'نعم, تصويت',
                        cancelButtonText: 'إلغاء'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            document.getElementById('localListForm').submit();
                        }
                    });
                } else {
                    document.getElementById('localListForm').submit();
                }
            });
        });
    </script>
</body>
</html>

E-voting System/E-voting System/Views/user/Login.cshtml
@model E_voting_System.Models.USER

@{
    ViewBag.Title = "Login";
}

<style>
    body, h1, h2, h3, h4, h5, h6 h2, button {
        font-family: 'Cairo', sans-serif;
    }

    .login-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: white;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        border-radius: 8px;
        padding: 20px;
        max-width: 1100px; /* Increase the width here */
        height: max-content;
        margin: auto;
    }

    .login-image {
        flex: 1;
        max-width: 45%;
        margin-right: 20px;
    }

        .login-image img {
            width: 100%;
            height: auto;
            border-radius: 8px;
        }

    .login-form-wrapper {
        flex: 1;
        max-width: 50%;
    }

    .loggin_button {
        text-align: center;
    }

    .line {
        border-bottom: 3px solid red;
        margin-top: 3px;
        width: 70%;
    }

    .line2 {
        border-bottom: 3px solid darkgreen;
        margin-top: 3px;
        width: 60%;
    }
</style>

<!-- Login Section ====================== -->
<br />
<center>
    <h2>تسجيل الدخول</h2><center><div class="line2"></div><div class="line"></div></center>
</center>

<section class="section-login pt-60 pt-lg-100 pt-xxl-120 pb-40">
    <div class="container">
        <div class="login-container">
            <div class="login-image">
                <img src="~/Content/images/product/Screenshot_2024-08-21_143730.png" alt="Login Image" />
            </div>

            <div class="login-form-wrapper bg-custom-light p-4 p-lg-40" style="background-color:white !important;">

                @using (Html.BeginForm("Login", "user", FormMethod.Post, new { id = "loginForm", @class = "login-form row g-30 wow slideInUp" }))
                {
                    @Html.AntiForgeryToken()
                    <br /><br />
                    <div class="col-md-12 mb-3">
                        <br /><br /><br /> <label for="National_ID" class="form-label" style="display: flex; justify-content:center; color: black; font-size:21px">الرقم الوطني</label>
                        @Html.EditorFor(model => model.National_ID, new { htmlAttributes = new { @class = "form-control", id = "National_ID", required = "" } })
                        @Html.ValidationMessageFor(model => model.National_ID, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-12 mt-4 loggin_button">
                        <button type="submit" class="btn btn-primary btn-block" style="font-family: 'Cairo', sans-serif;">تسجيل الدخول</button>
                    </div>
                    <div class="response py-1"></div>
                }
            </div>
            <!-- login-form-wrapper -->
        </div>
        <!-- login-container -->
    </div>
    <!-- container -->
</section>
<!-- Login Section ====================== -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#loginForm').on('submit', function (e) {
                e.preventDefault();
                // Add any additional client-side validation or AJAX form submission logic here
                var isValid = true;
                if ($('#National_ID').val().trim() === '') {
                    $('#National_ID').addClass('is-invalid');
                    isValid = false;
                } else {
                    $('#National_ID').removeClass('is-invalid');
                }

                if (isValid) {
                    this.submit();
                }
            });
        });
    </script>
}

E-voting System/E-voting System/Views/user/LoginWithPassword.cshtml
@{
    ViewBag.Title = "Login with Password";
}
<style>
    body, h2 {
        font-family: 'Cairo', sans-serif;
    }

    .line {
        border-bottom: 3px solid red;
        margin-top: 3px;
        width: 70%;
    }

    .line2 {
        border-bottom: 3px solid darkgreen;
        margin-top: 3px;
        width: 60%;
    }

    .d {
        display: flex;
        justify-content: flex-start;
    }
</style>
<br />
<br />
<br />
<center>
   
    <h2>تسجيل الدخول</h2><center><div class="line2"></div><div class="line"></div></center>
</center>
<br />
<br />
<div class="d-flex justify-content-center align-items-center">
    <div class="card shadow-lg" style="width: 40%; border-radius: 10px;">
        <div class="card-body">
            @using (Html.BeginForm("LoginWithPassword", "user", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group mb-3">
                        <label for="National_ID" class="form-label" style="display: flex; justify-content: space-evenly; ">الرقم الوطني</label>
                        <input type="text" id="National_ID" name="National_ID" class="form-control" value="@ViewBag.NationalId" />
                        <span class="text-danger">@ViewBag.NationalIdError</span>
                    </div>

                    <div class="form-group mb-3">
                        <label for="Password" class="form-label" style="display: flex; justify-content: space-evenly; ">كلمة المرور</label>
                        <input type="password" id="Password" name="Password" class="form-control" />
                        <span class="text-danger">@ViewBag.PasswordError</span>
                    </div>

                    <div class="form-group text-center">
                        <br />
                        <input type="submit" value="تسجيل الدخول" class="btn btn-primary" style=" font-family: 'Cairo', sans-serif; " />
                    </div>

                    <span class="text-danger font-weight-bold d-block text-center mt-3">@ViewBag.auth</span>
                </div>
            }
        </div>
    </div>
</div>